name: CI
on: push
jobs:
  run:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 3.1
          - 3.2
          - 3.3
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Rspec
        run: |
          gem install bundler
          bundle install
          bundle exec rspec -fdoc
